package redactov.frb.datagen;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.registry.tag.BlockTags;
import redactov.frb.block.ModBlocks;
import redactov.frb.util.ModTags;

import java.util.concurrent.CompletableFuture;

public class ModBlockTagProvider extends FabricTagProvider.BlockTagProvider {
    public ModBlockTagProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> registriesFuture) {
        super(output,registriesFuture);
    }


    @Override
    protected void configure(RegistryWrapper.WrapperLookup arg) {

        getOrCreateTagBuilder(BlockTags.AXE_MINEABLE)
                .add(ModBlocks.WHITE_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.ORANGE_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.MAGENTA_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.LIGHT_BLUE_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.YELLOW_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.LIME_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.PINK_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.GRAY_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.LIGHT_GRAY_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.CYAN_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.PURPLE_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.BLUE_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.BROWN_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.GREEN_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.RED_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.BLACK_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.WHITE_WALL_PLANKS)
                .add(ModBlocks.ORANGE_WALL_PLANKS)
                .add(ModBlocks.MAGENTA_WALL_PLANKS)
                .add(ModBlocks.LIGHT_BLUE_WALL_PLANKS)
                .add(ModBlocks.YELLOW_WALL_PLANKS)
                .add(ModBlocks.LIME_WALL_PLANKS)
                .add(ModBlocks.PINK_WALL_PLANKS)
                .add(ModBlocks.GRAY_WALL_PLANKS)
                .add(ModBlocks.LIGHT_GRAY_WALL_PLANKS)
                .add(ModBlocks.CYAN_WALL_PLANKS)
                .add(ModBlocks.PURPLE_WALL_PLANKS)
                .add(ModBlocks.BLUE_WALL_PLANKS)
                .add(ModBlocks.BROWN_WALL_PLANKS)
                .add(ModBlocks.GREEN_WALL_PLANKS)
                .add(ModBlocks.RED_WALL_PLANKS)
                .add(ModBlocks.BLACK_WALL_PLANKS);

        getOrCreateTagBuilder(BlockTags.PICKAXE_MINEABLE)
                .add(ModBlocks.BRICKS)
                .add(ModBlocks.BRICKS_OLD_A)
                .add(ModBlocks.BRICKS_OLD_B)
                .add(ModBlocks.WHITE_BRICKS)
                .add(ModBlocks.ORANGE_BRICKS)
                .add(ModBlocks.BROWN_BRICKS)
                .add(ModBlocks.DARK_BRICKS)
                .add(ModBlocks.STONE_PLATE)
                .add(ModBlocks.STONE_PLATE_GREY)
                .add(ModBlocks.STONE_PLATE_LIGHT_GREY)
                .add(ModBlocks.STONE_PLATE_WHITE)
                .add(ModBlocks.STONE_PLATE_WHITE_COLORB)
                .add(ModBlocks.STONE_PLATE_WHITE_COLORC)
                .add(ModBlocks.STONE_PLATE_YELLOW)
                .add(ModBlocks.STONE_PLATE_DARK_YELLOW)

                .add(ModBlocks.BRICK_PLATE)
                .add(ModBlocks.BRICK_PLATE_DESERT)
                .add(ModBlocks.BRICK_PLATE_OLD)
                .add(ModBlocks.BRICK_PLATE_OLD_MOSSY)
                .add(ModBlocks.BRICK_PLATE_MOSSY)
                .add(ModBlocks.BRICK_PLATE_BROWN)
                .add(ModBlocks.BRICK_PLATE_WHITE)
                .add(ModBlocks.BRICK_PLATE_YELLOW)
                .add(ModBlocks.BRICK_PLATE_GREY)
                .add(ModBlocks.BRICK_PLATE_DARK_YELLOW)

                .add(ModBlocks.OAK_PLANKS_A)
                .add(ModBlocks.OAK_PLANKS_B)
                .add(ModBlocks.OAK_PLANKS_C)
                .add(ModBlocks.STRIPPED_OAK_PLANKS)
                .add(ModBlocks.SPRUCE_PLANKS)
                .add(ModBlocks.ACACIA_PLANKS)

                .add(ModBlocks.WHITE_CONCRETE_A)
                .add(ModBlocks.WHITE_CONCRETE_B)
                .add(ModBlocks.WHITE_CONCRETE_C)
                .add(ModBlocks.WHITE_CONCRETE_D)
                .add(ModBlocks.ORANGE_CONCRETE_A)
                .add(ModBlocks.ORANGE_CONCRETE_B)
                .add(ModBlocks.ORANGE_CONCRETE_C)
                .add(ModBlocks.ORANGE_CONCRETE_D)
                .add(ModBlocks.MAGENTA_CONCRETE_A)
                .add(ModBlocks.MAGENTA_CONCRETE_B)
                .add(ModBlocks.MAGENTA_CONCRETE_C)
                .add(ModBlocks.MAGENTA_CONCRETE_D)
                .add(ModBlocks.LIGHT_BLUE_CONCRETE_A)
                .add(ModBlocks.LIGHT_BLUE_CONCRETE_B)
                .add(ModBlocks.LIGHT_BLUE_CONCRETE_C)
                .add(ModBlocks.LIGHT_BLUE_CONCRETE_D)
                .add(ModBlocks.YELLOW_CONCRETE_A)
                .add(ModBlocks.YELLOW_CONCRETE_B)
                .add(ModBlocks.YELLOW_CONCRETE_C)
                .add(ModBlocks.YELLOW_CONCRETE_D)
                .add(ModBlocks.LIME_CONCRETE_A)
                .add(ModBlocks.LIME_CONCRETE_B)
                .add(ModBlocks.LIME_CONCRETE_C)
                .add(ModBlocks.LIME_CONCRETE_D)
                .add(ModBlocks.PINK_CONCRETE_A)
                .add(ModBlocks.PINK_CONCRETE_B)
                .add(ModBlocks.PINK_CONCRETE_C)
                .add(ModBlocks.PINK_CONCRETE_D)
                .add(ModBlocks.GRAY_CONCRETE_A)
                .add(ModBlocks.GRAY_CONCRETE_B)
                .add(ModBlocks.GRAY_CONCRETE_C)
                .add(ModBlocks.GRAY_CONCRETE_D)
                .add(ModBlocks.LIGHT_GRAY_CONCRETE_A)
                .add(ModBlocks.LIGHT_GRAY_CONCRETE_B)
                .add(ModBlocks.LIGHT_GRAY_CONCRETE_C)
                .add(ModBlocks.LIGHT_GRAY_CONCRETE_D)
                .add(ModBlocks.CYAN_CONCRETE_A)
                .add(ModBlocks.CYAN_CONCRETE_B)
                .add(ModBlocks.CYAN_CONCRETE_C)
                .add(ModBlocks.CYAN_CONCRETE_D)
                .add(ModBlocks.PURPLE_CONCRETE_A)
                .add(ModBlocks.PURPLE_CONCRETE_B)
                .add(ModBlocks.PURPLE_CONCRETE_C)
                .add(ModBlocks.PURPLE_CONCRETE_D)
                .add(ModBlocks.BLUE_CONCRETE_A)
                .add(ModBlocks.BLUE_CONCRETE_B)
                .add(ModBlocks.BLUE_CONCRETE_C)
                .add(ModBlocks.BLUE_CONCRETE_D)
                .add(ModBlocks.BROWN_CONCRETE_A)
                .add(ModBlocks.BROWN_CONCRETE_B)
                .add(ModBlocks.BROWN_CONCRETE_C)
                .add(ModBlocks.BROWN_CONCRETE_D)
                .add(ModBlocks.GREEN_CONCRETE_A)
                .add(ModBlocks.GREEN_CONCRETE_B)
                .add(ModBlocks.GREEN_CONCRETE_C)
                .add(ModBlocks.GREEN_CONCRETE_D)
                .add(ModBlocks.RED_CONCRETE_A)
                .add(ModBlocks.RED_CONCRETE_B)
                .add(ModBlocks.RED_CONCRETE_C)
                .add(ModBlocks.RED_CONCRETE_D)
                .add(ModBlocks.BLACK_CONCRETE_A)
                .add(ModBlocks.BLACK_CONCRETE_B)
                .add(ModBlocks.BLACK_CONCRETE_C)
                .add(ModBlocks.BLACK_CONCRETE_D)


                .add(ModBlocks.FACTORY_PLATE_WHITE)
                .add(ModBlocks.FACTORY_PLATE_GREY)
                .add(ModBlocks.VENTILATION)
                .add(ModBlocks.RUST_VENTILATION)
                .add(ModBlocks.GARAGE_DOOR)
                .add(ModBlocks.RUST_GARAGE_DOOR)
                .add(ModBlocks.DANGER_BLOCK)
                .add(ModBlocks.ELECTRIC_PANEL)
                .add(ModBlocks.ELECTRIC_PANEL_B)
                .add(ModBlocks.INDUSTRIAL_LAMP)
                .add(ModBlocks.NUCLEAR_BLOCK)
                .add(ModBlocks.COBBLE)
                .add(ModBlocks.COBBLE_DARK)
                .add(ModBlocks.COBBLE_LIGHT)
                .add(ModBlocks.DECO_COBBLE)
                .add(ModBlocks.MOSSY_COBBLE)

                .add(ModBlocks.STONE_A)
                .add(ModBlocks.STONE_B)
                .add(ModBlocks.STONE_C)
                .add(ModBlocks.SMOOTH_STONE_A)
                .add(ModBlocks.SMOOTH_STONE_B)
                .add(ModBlocks.SMOOTH_STONE_C)
                .add(ModBlocks.DIRTY_STONE);
        
        
        getOrCreateTagBuilder(BlockTags.SHOVEL_MINEABLE)
                .add(ModBlocks.GRAVEL)
                .add(ModBlocks.GRASS)
                .add(ModBlocks.DIRT)
                .add(ModBlocks.SOIL_A);



        getOrCreateTagBuilder(BlockTags.NEEDS_IRON_TOOL)

                .add(ModBlocks.COBBLE)
                .add(ModBlocks.COBBLE_DARK)
                .add(ModBlocks.COBBLE_LIGHT)
                .add(ModBlocks.DECO_COBBLE)
                .add(ModBlocks.MOSSY_COBBLE)
                .add(ModBlocks.STONE_A)
                .add(ModBlocks.STONE_B)
                .add(ModBlocks.STONE_C)
                .add(ModBlocks.SMOOTH_STONE_A)
                .add(ModBlocks.SMOOTH_STONE_B)
                .add(ModBlocks.SMOOTH_STONE_C)
                .add(ModBlocks.DIRTY_STONE)

                .add(ModBlocks.BRICKS)
                .add(ModBlocks.BRICKS_OLD_A)
                .add(ModBlocks.BRICKS_OLD_B)
                .add(ModBlocks.WHITE_BRICKS)
                .add(ModBlocks.ORANGE_BRICKS)
                .add(ModBlocks.BROWN_BRICKS)
                .add(ModBlocks.DARK_BRICKS)
                .add(ModBlocks.STONE_PLATE)
                .add(ModBlocks.STONE_PLATE_GREY)
                .add(ModBlocks.STONE_PLATE_LIGHT_GREY)
                .add(ModBlocks.STONE_PLATE_WHITE)
                .add(ModBlocks.STONE_PLATE_WHITE_COLORB)
                .add(ModBlocks.STONE_PLATE_WHITE_COLORC)
                .add(ModBlocks.STONE_PLATE_YELLOW)
                .add(ModBlocks.STONE_PLATE_DARK_YELLOW)

                .add(ModBlocks.BRICK_PLATE)
                .add(ModBlocks.BRICK_PLATE_DESERT)
                .add(ModBlocks.BRICK_PLATE_OLD)
                .add(ModBlocks.BRICK_PLATE_OLD_MOSSY)
                .add(ModBlocks.BRICK_PLATE_MOSSY)
                .add(ModBlocks.BRICK_PLATE_BROWN)
                .add(ModBlocks.BRICK_PLATE_WHITE)
                .add(ModBlocks.BRICK_PLATE_YELLOW)
                .add(ModBlocks.BRICK_PLATE_GREY)
                .add(ModBlocks.BRICK_PLATE_DARK_YELLOW)

                .add(ModBlocks.OAK_PLANKS_A)
                .add(ModBlocks.OAK_PLANKS_B)
                .add(ModBlocks.OAK_PLANKS_C)
                .add(ModBlocks.STRIPPED_OAK_PLANKS)
                .add(ModBlocks.SPRUCE_PLANKS)
                .add(ModBlocks.ACACIA_PLANKS)

                .add(ModBlocks.WHITE_CONCRETE_A)
                .add(ModBlocks.WHITE_CONCRETE_B)
                .add(ModBlocks.WHITE_CONCRETE_C)
                .add(ModBlocks.WHITE_CONCRETE_D)
                .add(ModBlocks.ORANGE_CONCRETE_A)
                .add(ModBlocks.ORANGE_CONCRETE_B)
                .add(ModBlocks.ORANGE_CONCRETE_C)
                .add(ModBlocks.ORANGE_CONCRETE_D)
                .add(ModBlocks.MAGENTA_CONCRETE_A)
                .add(ModBlocks.MAGENTA_CONCRETE_B)
                .add(ModBlocks.MAGENTA_CONCRETE_C)
                .add(ModBlocks.MAGENTA_CONCRETE_D)
                .add(ModBlocks.LIGHT_BLUE_CONCRETE_A)
                .add(ModBlocks.LIGHT_BLUE_CONCRETE_B)
                .add(ModBlocks.LIGHT_BLUE_CONCRETE_C)
                .add(ModBlocks.LIGHT_BLUE_CONCRETE_D)
                .add(ModBlocks.YELLOW_CONCRETE_A)
                .add(ModBlocks.YELLOW_CONCRETE_B)
                .add(ModBlocks.YELLOW_CONCRETE_C)
                .add(ModBlocks.YELLOW_CONCRETE_D)
                .add(ModBlocks.LIME_CONCRETE_A)
                .add(ModBlocks.LIME_CONCRETE_B)
                .add(ModBlocks.LIME_CONCRETE_C)
                .add(ModBlocks.LIME_CONCRETE_D)
                .add(ModBlocks.PINK_CONCRETE_A)
                .add(ModBlocks.PINK_CONCRETE_B)
                .add(ModBlocks.PINK_CONCRETE_C)
                .add(ModBlocks.PINK_CONCRETE_D)
                .add(ModBlocks.GRAY_CONCRETE_A)
                .add(ModBlocks.GRAY_CONCRETE_B)
                .add(ModBlocks.GRAY_CONCRETE_C)
                .add(ModBlocks.GRAY_CONCRETE_D)
                .add(ModBlocks.LIGHT_GRAY_CONCRETE_A)
                .add(ModBlocks.LIGHT_GRAY_CONCRETE_B)
                .add(ModBlocks.LIGHT_GRAY_CONCRETE_C)
                .add(ModBlocks.LIGHT_GRAY_CONCRETE_D)
                .add(ModBlocks.CYAN_CONCRETE_A)
                .add(ModBlocks.CYAN_CONCRETE_B)
                .add(ModBlocks.CYAN_CONCRETE_C)
                .add(ModBlocks.CYAN_CONCRETE_D)
                .add(ModBlocks.PURPLE_CONCRETE_A)
                .add(ModBlocks.PURPLE_CONCRETE_B)
                .add(ModBlocks.PURPLE_CONCRETE_C)
                .add(ModBlocks.PURPLE_CONCRETE_D)
                .add(ModBlocks.BLUE_CONCRETE_A)
                .add(ModBlocks.BLUE_CONCRETE_B)
                .add(ModBlocks.BLUE_CONCRETE_C)
                .add(ModBlocks.BLUE_CONCRETE_D)
                .add(ModBlocks.BROWN_CONCRETE_A)
                .add(ModBlocks.BROWN_CONCRETE_B)
                .add(ModBlocks.BROWN_CONCRETE_C)
                .add(ModBlocks.BROWN_CONCRETE_D)
                .add(ModBlocks.GREEN_CONCRETE_A)
                .add(ModBlocks.GREEN_CONCRETE_B)
                .add(ModBlocks.GREEN_CONCRETE_C)
                .add(ModBlocks.GREEN_CONCRETE_D)
                .add(ModBlocks.RED_CONCRETE_A)
                .add(ModBlocks.RED_CONCRETE_B)
                .add(ModBlocks.RED_CONCRETE_C)
                .add(ModBlocks.RED_CONCRETE_D)
                .add(ModBlocks.BLACK_CONCRETE_A)
                .add(ModBlocks.BLACK_CONCRETE_B)
                .add(ModBlocks.BLACK_CONCRETE_C)
                .add(ModBlocks.BLACK_CONCRETE_D)

                .add(ModBlocks.WHITE_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.ORANGE_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.MAGENTA_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.LIGHT_BLUE_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.YELLOW_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.LIME_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.PINK_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.GRAY_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.LIGHT_GRAY_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.CYAN_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.PURPLE_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.BLUE_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.BROWN_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.GREEN_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.RED_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.BLACK_WALL_PLANKS_VERTICAL)
                .add(ModBlocks.WHITE_WALL_PLANKS)
                .add(ModBlocks.ORANGE_WALL_PLANKS)
                .add(ModBlocks.MAGENTA_WALL_PLANKS)
                .add(ModBlocks.LIGHT_BLUE_WALL_PLANKS)
                .add(ModBlocks.YELLOW_WALL_PLANKS)
                .add(ModBlocks.LIME_WALL_PLANKS)
                .add(ModBlocks.PINK_WALL_PLANKS)
                .add(ModBlocks.GRAY_WALL_PLANKS)
                .add(ModBlocks.LIGHT_GRAY_WALL_PLANKS)
                .add(ModBlocks.CYAN_WALL_PLANKS)
                .add(ModBlocks.PURPLE_WALL_PLANKS)
                .add(ModBlocks.BLUE_WALL_PLANKS)
                .add(ModBlocks.BROWN_WALL_PLANKS)
                .add(ModBlocks.GREEN_WALL_PLANKS)
                .add(ModBlocks.RED_WALL_PLANKS)
                .add(ModBlocks.BLACK_WALL_PLANKS)

                .add(ModBlocks.FACTORY_PLATE_WHITE)
                .add(ModBlocks.FACTORY_PLATE_GREY)
                .add(ModBlocks.VENTILATION)
                .add(ModBlocks.RUST_VENTILATION)
                .add(ModBlocks.GARAGE_DOOR)
                .add(ModBlocks.RUST_GARAGE_DOOR)
                .add(ModBlocks.DANGER_BLOCK)
                .add(ModBlocks.ELECTRIC_PANEL)
                .add(ModBlocks.ELECTRIC_PANEL_B)
                .add(ModBlocks.INDUSTRIAL_LAMP)
                .add(ModBlocks.NUCLEAR_BLOCK);

    }
}
